before_commands:
    - "composer install --prefer-source"

tools:
    external_code_coverage: true
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
        filter:
            paths: ["src/*"]
    php_cpd:
        enabled: true
        excluded_dirs: ["/tests/", "vendor"]
    php_cs_fixer:
        enabled: false
        config:
            level: all
        filter:
            paths: ["src/*", "/tests/*"]
    php_loc:
        enabled: true
    php_mess_detector:
        enabled: true
        filter:
            paths: ["/tests/*"]
    php_pdepend:
        enabled: true
        excluded_dirs: ["/tests/", "vendor"]
    php_analyzer:
        filter:
            paths: ["src/*", "/tests/*"]
    sensiolabs_security_checker: true

checks:
    php:
        deadlock_detection_in_loops: true
        deprecated_code_usage: true
        duplication: true
        encourage_postdec_operator: true
        encourage_shallow_comparison: true
        encourage_single_quotes: true
        fix_doc_comments: true
        fix_line_ending: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: false
            order_alphabetically: false
        foreach_traversable: true
        function_in_camel_caps: true
        instanceof_class_exists: true
        line_length:
            max_length: '120'
        method_calls_on_non_object: true
        missing_arguments: true
        more_specific_types_in_doc_comments: true
        newline_at_end_of_file: true
        no_commented_out_code: true
        no_debug_code: true
        no_duplicate_arguments: true
        no_empty_statements: true
        no_error_suppression: true
        no_eval: true
        no_exit: true
        no_global_keyword: true
        no_goto: true
        no_long_variable_names:
            maximum: '20'
        no_non_implemented_abstract_methods: true
        no_property_on_interface: true
        no_short_open_tag: true
        no_short_variable_names:
            minimum: '3'
        no_trailing_whitespace: true
        no_trait_type_hints: true
        no_underscore_prefix_in_methods: true
        no_underscore_prefix_in_properties: true
        no_unnecessary_final_modifier: true
        no_unnecessary_if: true
        non_commented_empty_catch_block: true
        one_class_per_file: true
        optional_parameters_at_the_end: true
        overriding_private_members: true
        param_doc_comment_if_not_inferrable: true
        parameter_doc_comments: true
        parameter_non_unique: true
        parameters_in_camelcaps: true
        php5_style_constructor: true
        parse_doc_comments: true
        phpunit_assertions: true
        precedence_in_conditions: true
        precedence_mistakes: true
        prefer_while_loop_over_for_loop: true
        properties_in_camelcaps: true
        property_assignments: true
        psr2_class_declaration: true
        psr2_control_structure_declaration: true
        psr2_switch_declaration: true
        remove_extra_empty_lines: true
        require_php_tag_first: true
        require_scope_for_methods: true
        require_scope_for_properties: true
        return_doc_comment_if_not_inferrable: true
        return_doc_comments: true
        security_vulnerabilities: true
        side_effects_or_types: true
        simplify_boolean_return: true
        single_namespace_per_use: true
        switch_fallthrough_commented: true
        sql_injection_vulnerabilities: true
        symfony_request_injection: true
        too_many_arguments: true
        unreachable_code: true
        unused_methods: true
        unused_parameters: true
        unused_properties: true
        unused_variables: true
        uppercase_constants: true
        use_self_instead_of_fqcn: true
        use_statement_alias_conflict: true
        useless_calls: true
        variable_existence: true
        verify_access_scope_valid: true
        verify_argument_usable_as_reference: true
        verify_property_names: true
        code_rating: true
        closure_use_not_conflicting: true
        closure_use_modifiable: true
        classes_in_camel_caps: true
        catch_class_exists: true
        blank_line_after_namespace_declaration: true
        avoid_useless_overridden_methods: true
        avoid_usage_of_logical_operators: true
        avoid_unnecessary_concatenation: true
        avoid_todo_comments: true
        avoid_superglobals: true
        avoid_perl_style_comments: true
        avoid_multiple_statements_on_same_line: true
        avoid_length_functions_in_loops: true
        avoid_fixme_comments: true
        avoid_duplicate_types: true
        avoid_corrupting_byteorder_marks: true
        avoid_conflicting_incrementers: true
        avoid_closing_tag: true
        avoid_aliased_php_functions: true
        assignment_of_null_return: true
        argument_type_checks: true
        align_assignments: true